# Generated by Django 4.2.29 on 2026-03-27 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TraderWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=120, verbose_name="Название аккаунта"),
                ),
                ("address", models.CharField(max_length=42, verbose_name="Адрес 0x…")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trader_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Кошелёк трейдера",
                "verbose_name_plural": "Кошельки трейдеров",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="FundsOperationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deposit", "Депозит на Hyperliquid"),
                            ("withdraw", "Вывод с Hyperliquid"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("eth_ethereum", "ETH → Ethereum (Unit)"),
                            ("usdc_arbitrum", "USDC через bridge (Arbitrum)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=24)),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Комментарий"
                    ),
                ),
                ("compliance_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "middleoffice_approved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compliance_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_approved_ops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "middleoffice_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="middleoffice_approved_ops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="trading.traderwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка (депозит / вывод)",
                "verbose_name_plural": "Заявки (депозит / вывод)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="traderwallet",
            constraint=models.UniqueConstraint(
                fields=("user", "address"), name="unique_wallet_address_per_user"
            ),
        ),
    ]
