# Generated by Django 4.2.29 on 2026-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traderwallet",
            name="trading_key_encrypted",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Fernet; не редактировать вручную.",
                verbose_name="Ключ для ордеров (зашифровано)",
            ),
        ),
    ]
