# Generated by Django 4.2.29 on 2026-03-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_traderwallet_trading_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundsoperationrequest",
            name="blockchain_tx_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="0x… после исполнения (Arbitrum или Ethereum в зависимости от маршрута).",
                max_length=80,
                verbose_name="Хеш транзакции в блокчейне",
            ),
        ),
    ]
