"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-dev-key-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

# Пустая строка в env (ALLOWED_HOSTS=) подставляет "" вместо default → список хостов пустой → падение/400.
_allowed_raw = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost")
if not str(_allowed_raw).strip():
    _allowed_raw = "127.0.0.1,localhost"
ALLOWED_HOSTS = [
    host.strip() for host in str(_allowed_raw).split(",") if host.strip()
]
# Один прод-домен из env (без схемы): дополняет ALLOWED_HOSTS и ниже даёт CSRF через перебор хостов.
_public_domain = os.environ.get("PUBLIC_DOMAIN", "").strip()
if _public_domain:
    if _public_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_public_domain)
    if not _public_domain.startswith("www."):
        _www_host = f"www.{_public_domain}"
        if _www_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_www_host)
_render = os.environ.get("RENDER", "").lower() in ("true", "1", "yes")
# На Render: RENDER_EXTERNAL_HOSTNAME=xxx.onrender.com; если пусто — пробуем RENDER_SERVICE_URL (https://…onrender.com).
_ext = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if not _ext and _render:
    for _url in (
        os.environ.get("RENDER_SERVICE_URL", "").strip(),
        os.environ.get("RENDER_EXTERNAL_URL", "").strip(),
    ):
        if _url:
            _netloc = urlparse(_url).netloc
            if _netloc:
                _ext = _netloc
                break
if _ext and _ext not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_ext)
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
# Локально (не Render): всегда допускаем эти хосты — иначе при DEBUG=False в .env будет 400/403.
if not _render:
    for _h in ("127.0.0.1", "localhost", "[::1]"):
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)
CSRF_TRUSTED_ORIGINS = [
    origin.strip().rstrip("/")
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


def _add_csrf_origin(origins: list, value: str) -> None:
    v = (value or "").strip().rstrip("/")
    if v and v not in origins:
        origins.append(v)


# Полный URL сервиса (Render / свой домен) — origin со схемой и портом, если есть.
for _url_key in (
    "PUBLIC_URL",
    "SITE_URL",
    "RENDER_SERVICE_URL",
    "RENDER_EXTERNAL_URL",
):
    _raw = os.environ.get(_url_key, "").strip()
    if not _raw:
        continue
    _p = urlparse(_raw if "://" in _raw else f"https://{_raw}")
    if _p.scheme and _p.netloc:
        _add_csrf_origin(CSRF_TRUSTED_ORIGINS, f"{_p.scheme}://{_p.netloc}")

# Django 4+: заголовок Origin при POST должен совпадать с одним из доверенных origin.
if _ext:
    _https_origin = f"https://{_ext}"
    _add_csrf_origin(CSRF_TRUSTED_ORIGINS, _https_origin)
for _dev in (
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8001",
    "http://localhost:8001",
    "http://[::1]:8000",
    "http://[::1]:8001",
    "http://127.0.0.1:8080",
    "http://localhost:8080",
    "http://127.0.0.1:5000",
    "http://localhost:5000",
    "http://localhost:3000",
    "https://127.0.0.1:8000",
    "https://localhost:8000",
):
    _add_csrf_origin(CSRF_TRUSTED_ORIGINS, _dev)

# Локально (не Render): порты runserver 8000–8020 — иначе при DEBUG=False в .env будет 403 CSRF.
if not _render:
    for _port in range(8000, 8021):
        for _host in ("127.0.0.1", "localhost", "[::1]"):
            _add_csrf_origin(CSRF_TRUSTED_ORIGINS, f"http://{_host}:{_port}")
            _add_csrf_origin(CSRF_TRUSTED_ORIGINS, f"https://{_host}:{_port}")

# Каждый хост из ALLOWED_HOSTS — с http и https (без порта; для нестандартного порта задайте CSRF_TRUSTED_ORIGINS).
for _h in list(ALLOWED_HOSTS):
    if not _h or _h == "*" or _h.startswith("."):
        continue
    for _scheme in ("http://", "https://"):
        _add_csrf_origin(CSRF_TRUSTED_ORIGINS, f"{_scheme}{_h}")

# За Render / nginx с HTTPS: иначе request.is_secure() ложен, схема в редиректах/CSRF может ломаться.
_use_https_proxy = _render or os.environ.get(
    "USE_HTTPS_BEHIND_PROXY", ""
).lower() in ("true", "1", "yes")
if not _use_https_proxy:
    for _uk in ("PUBLIC_URL", "SITE_URL"):
        _ru = (os.environ.get(_uk) or "").strip()
        if _ru.lower().startswith("https://"):
            _use_https_proxy = True
            break
if _use_https_proxy:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Включайте только если за прокси ломается Host; иначе X-Forwarded-Host иногда даёт несовпадение с Origin → 403 CSRF.
if os.environ.get("USE_X_FORWARDED_HOST", "").lower() in ("true", "1", "yes"):
    USE_X_FORWARDED_HOST = True

# Secure-cookies за HTTPS (Render / FORCE_SECURE_COOKIES). Финальное значение — после DATABASES:
# при sqlite локально не ставим Secure, даже если RENDER=true в .env скопирован с продакшена.
_use_secure_cookies = _render or os.environ.get(
    "FORCE_SECURE_COOKIES", ""
).lower() in ("true", "1", "yes")
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "people",
    "trading",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "trading.middleware.HyperliquidNetworkMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "trading.context_processors.roles",
                "trading.context_processors.active_trader_wallet_ctx",
                "trading.context_processors.funds_operation_feed",
                "trading.context_processors.hyperliquid_network",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
# Postgres на Render / Heroku и т.п. (переменная DATABASE_URL)
if os.environ.get("DATABASE_URL"):
    DATABASES["default"] = dj_database_url.config(
        conn_max_age=600,
        ssl_require=os.environ.get("DATABASE_SSL_REQUIRE", "true").lower() == "true",
    )

_engine = DATABASES["default"].get("ENGINE", "")
_sqlite = "sqlite" in _engine.lower()
_override_insecure = os.environ.get("USE_INSECURE_COOKIES", "").lower() in (
    "true",
    "1",
    "yes",
)
# Postgres на localhost в .env + случайный RENDER=true из продакшена — иначе Secure cookie не уходит по HTTP.
_dburl = os.environ.get("DATABASE_URL", "")
_local_db_url = bool(
    _dburl
    and any(x in _dburl.lower() for x in ("localhost", "127.0.0.1", "::1"))
)
if not _render or _sqlite or _override_insecure or _local_db_url:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
else:
    CSRF_COOKIE_SECURE = _use_secure_cookies
    SESSION_COOKIE_SECURE = _use_secure_cookies

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Подпись ордеров HL: только env, не ввод в браузере. Совпадает с HYPERLIQUID_PRIVATE_KEY в hyperliquid_account.
HYPERLIQUID_TRADING_PRIVATE_KEY = (
    os.environ.get("HYPERLIQUID_TRADING_PRIVATE_KEY", "").strip()
    or os.environ.get("HYPERLIQUID_PRIVATE_KEY", "").strip()
)

# Testnet: export HYPERLIQUID_USE_TESTNET=true — тот же ключ, что и для app.hyperliquid-testnet (Arbitrum Sepolia).
HYPERLIQUID_USE_TESTNET = os.environ.get("HYPERLIQUID_USE_TESTNET", "").lower() in (
    "1",
    "true",
    "yes",
)
HYPERLIQUID_MAINNET_INFO_URL = os.environ.get(
    "HYPERLIQUID_MAINNET_INFO_URL",
    "https://api.hyperliquid.xyz/info",
)
HYPERLIQUID_TESTNET_INFO_URL = os.environ.get(
    "HYPERLIQUID_TESTNET_INFO_URL",
    "https://api.hyperliquid-testnet.xyz/info",
)
# Обратная совместимость: один HYPERLIQUID_INFO_URL — для сети по умолчанию из env.
_legacy_hl_info = os.environ.get("HYPERLIQUID_INFO_URL", "").strip()
if _legacy_hl_info:
    if HYPERLIQUID_USE_TESTNET:
        HYPERLIQUID_TESTNET_INFO_URL = _legacy_hl_info
    else:
        HYPERLIQUID_MAINNET_INFO_URL = _legacy_hl_info
HYPERLIQUID_INFO_URL = (
    HYPERLIQUID_TESTNET_INFO_URL
    if HYPERLIQUID_USE_TESTNET
    else HYPERLIQUID_MAINNET_INFO_URL
)

# RPC для проверки FinalizedWithdrawal (Bridge2) при выводе USDC→Arbitrum.
ARBITRUM_ONE_RPC_URL = os.environ.get(
    "ARBITRUM_ONE_RPC_URL",
    "https://arb1.arbitrum.io/rpc",
)
ARBITRUM_SEPOLIA_RPC_URL = os.environ.get(
    "ARBITRUM_SEPOLIA_RPC_URL",
    "https://sepolia-rollup.arbitrum.io/rpc",
)

# Arbiscan API (getLogs) — лёгкая финализация USDC→Arbitrum без тяжёлого RPC в HTTP-запросе.
# Ключ: https://arbiscan.io/apis (бесплатный tier).
ARBITRUM_ARBISCAN_API_KEY = os.environ.get("ARBITRUM_ARBISCAN_API_KEY", "")
ARBITRUM_SEPOLIA_ARBISCAN_API_KEY = os.environ.get(
    "ARBITRUM_SEPOLIA_ARBISCAN_API_KEY",
    ARBITRUM_ARBISCAN_API_KEY,
)

# Депозит ETH через Unit (Ethereum L1): spotSend / deposit_eth в hyperliquid_account.
# Публичный RPC по умолчанию; при сбоях см. fallback в trading/funds_execution._web3_ethereum_l1.
# Переопределение: ETHEREUM_MAINNET_RPC_URL=https://...
ETHEREUM_MAINNET_RPC_URL = os.environ.get(
    "ETHEREUM_MAINNET_RPC_URL",
    "https://ethereum.publicnode.com",
)
ETHEREUM_SEPOLIA_RPC_URL = os.environ.get(
    "ETHEREUM_SEPOLIA_RPC_URL",
    "https://rpc.sepolia.org",
)

# Базовый URL API Unit (hyperunit.xyz). С IP датацентров (Render и др.) Cloudflare часто
# отвечает 403 даже с Origin/Referer — тогда разверните прокси (scripts/hyperunit-proxy-worker.js)
# и укажите здесь origin прокси, без завершающего слэша.
HYPERUNIT_MAINNET_API_URL = os.environ.get(
    "HYPERUNIT_MAINNET_API_URL",
    "https://api.hyperunit.xyz",
).rstrip("/")
HYPERUNIT_TESTNET_API_URL = os.environ.get(
    "HYPERUNIT_TESTNET_API_URL",
    "https://api.hyperunit-testnet.xyz",
).rstrip("/")

# Cloudflare на api.hyperunit.xyz часто режет IP любого хостинга/VPS. Тогда задайте JSON вручную
# (тот же ответ, что из ноутбука/браузера с «хорошего» IP): ключ — HL-адрес, значение — "address" Unit.
HYPERUNIT_ETH_DEPOSIT_ADDRESS_MAP_JSON = os.environ.get(
    "HYPERUNIT_ETH_DEPOSIT_ADDRESS_MAP_JSON",
    "",
).strip()
HYPERUNIT_ETH_DEPOSIT_ADDRESS_MAP_JSON_TESTNET = os.environ.get(
    "HYPERUNIT_ETH_DEPOSIT_ADDRESS_MAP_JSON_TESTNET",
    "",
).strip()

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Логи в stdout/stderr — в Render → Logs видно traceback при 500.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.environ.get("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
